---
- name: Add source.list file
  copy: src=webupd8team-java.list dest=/etc/apt/sources.list.d/webupd8team-java.list
  register: add_source_result
  become: yes

- name: Add apt-key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886
  become: yes

- name: Update apt cache
  apt: update_cache=yes
  when: add_source_result.changed == true
  become: yes

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
